version: '3.8'

services:
  app:
    build: .
    container_name: contest_app
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always

networks:
  default:
    name: contest_network
